// ACE 수업안 자동생성 유틸 — 템플릿 선택 + 40분 aceLesson 초안 생성 | 순수 함수 (훅 아님)

// --- 템플릿 정의 ---
const TEMPLATES = {
  A: {
    code: 'A',
    label: '기초탐색',
    minutes: { intro: 5, acquire: 15, challenge: 8, engage: 6, wrapup: 6 },
  },
  B: {
    code: 'B',
    label: '도전미션',
    minutes: { intro: 5, acquire: 10, challenge: 12, engage: 7, wrapup: 6 },
  },
  C: {
    code: 'C',
    label: '게임적용',
    minutes: { intro: 5, acquire: 8, challenge: 10, engage: 11, wrapup: 6 },
  },
  D: {
    code: 'D',
    label: '이론중심',
    minutes: { intro: 5, acquire: 15, challenge: 10, engage: 4, wrapup: 6 },
  },
}

/**
 * 활동 특성에 따라 최적 템플릿 코드를 선택한다.
 * 판별 순서: D(이론) → C(게임적용) → A(기초탐색) → B(도전미션, 기본값)
 */
export function selectTemplate(activity) {
  if (!activity) return 'B'

  const tags = activity.tags || []
  const fmsSkills = activity.fmsSkills || []
  const acePhase = activity.acePhase || ''
  const difficulty = activity.difficulty ?? 2

  // D: fmsSkills 비어있고 tags에 "이론"
  if (fmsSkills.length === 0 && tags.includes('이론')) return 'D'

  // C: acePhase="E" 또는 tags에 "게임"
  if (acePhase === 'E' || tags.includes('게임')) return 'C'

  // A: difficulty=1 또는 acePhase="A"
  if (difficulty === 1 || acePhase === 'A') return 'A'

  // B: 기본값
  return 'B'
}

/**
 * 활동 정보를 기반으로 40분 ACE 수업안 초안을 생성한다.
 * @param {object} activity - 활동 객체
 * @param {string} [templateCode] - 강제 지정 템플릿 코드 (미지정 시 자동 선택)
 * @returns {object} aceLesson 객체
 */
export function generateAceLesson(activity, templateCode) {
  const code = templateCode || selectTemplate(activity)
  const tmpl = TEMPLATES[code] || TEMPLATES.B
  const name = activity.name || '활동'
  const skills = (activity.fmsSkills || []).join(', ') || '기본 움직임'
  const equip = (activity.equipment || []).join(', ') || '없음'
  const flow = activity.flow || []

  return {
    totalMinutes: 40,
    intro: buildIntro(tmpl, name, skills),
    acquire: buildAcquire(tmpl, name, skills, equip, flow),
    challenge: buildChallenge(tmpl, name, skills),
    engage: buildEngage(tmpl, name, skills, equip),
    wrapup: buildWrapup(tmpl, name),
    _autoGenerated: true,
    _templateCode: code,
    _templateLabel: tmpl.label,
  }
}

/**
 * 활동에 aceLesson이 없으면 자동 생성하여 병합한 새 객체를 반환한다.
 * (원본 activity를 변경하지 않음)
 */
export function ensureAceLesson(activity) {
  if (!activity) return activity
  if (activity.aceLesson) return activity
  return { ...activity, aceLesson: generateAceLesson(activity) }
}

// --- 단계별 빌더 ---

function buildIntro(tmpl, name, skills) {
  return {
    minutes: tmpl.minutes.intro,
    flow: [
      '출석 확인 후 모둠 정렬',
      '준비운동: 손목·발목 돌리기 + 제자리 뛰기 2분',
      `오늘 학습 주제 안내: ${name}`,
    ],
    metaQuestion: `${name}을(를) 잘 하려면 어떤 움직임이 가장 중요할까?`,
  }
}

function buildAcquire(tmpl, name, skills, equip, flow) {
  const drills = []

  // 드릴 1: 기초 연습
  drills.push({
    name: `${skills} 기초 연습 (개인)`,
    description: flow[0]
      ? `${flow[0]} — 교사 시범 후 개인 연습`
      : `${skills} 기본 동작을 교사 시범 후 개인별로 연습한다.`,
    scaffolding: {
      down: '교사가 동작을 세분화하여 단계별로 시범한다.',
      up: '동작의 속도와 정확도를 높여 연습한다.',
    },
  })

  // 드릴 2: 짝/모둠 활동
  drills.push({
    name: `${skills} 짝 활동`,
    description: flow[1]
      ? `${flow[1]} — 짝과 번갈아 수행하며 피드백`
      : `짝과 번갈아 ${skills}을(를) 수행하며 서로 피드백을 주고받는다.`,
    scaffolding: {
      down: '관찰 포인트 체크리스트를 제공한다.',
      up: '피드백을 바탕으로 동작을 스스로 교정한다.',
    },
  })

  return {
    minutes: tmpl.minutes.acquire,
    goal: `${name}에 필요한 ${skills}의 기본 동작을 수행할 수 있다`,
    drills,
    feedback: [
      `${skills} 동작에서 가장 어려웠던 부분은?`,
      '짝의 동작과 내 동작이 어떻게 달랐어?',
    ],
  }
}

function buildChallenge(tmpl, name, skills) {
  const missions = [
    {
      name: `미션 1: 정확도 도전 (개인)`,
      description: `${skills} 동작을 5회 연속 정확하게 수행한다.`,
      minutes: Math.max(3, Math.floor(tmpl.minutes.challenge * 0.4)),
      scaffolding: {
        down: '3회로 줄여 도전한다.',
        up: '눈 감고 또는 비우세측으로 도전한다.',
      },
    },
    {
      name: `미션 2: 연속 수행 도전 (짝)`,
      description: `짝과 번갈아 ${skills}을(를) 이어서 수행하며 최대 횟수를 기록한다.`,
      minutes: Math.max(3, Math.floor(tmpl.minutes.challenge * 0.35)),
      scaffolding: {
        down: '쉬는 시간을 두고 수행한다.',
        up: '시간 제한을 두고 속도를 높인다.',
      },
    },
    {
      name: `미션 3: 창의 도전 (모둠)`,
      description: `모둠에서 ${name}을(를) 활용한 새로운 방법을 만들어 발표한다.`,
      minutes: Math.max(2, tmpl.minutes.challenge - Math.floor(tmpl.minutes.challenge * 0.4) - Math.floor(tmpl.minutes.challenge * 0.35)),
      scaffolding: {
        down: '교사가 예시를 1개 제공한다.',
        up: '조건(공간 제한, 인원 제한)을 추가하여 난이도를 높인다.',
      },
    },
  ]

  return {
    minutes: tmpl.minutes.challenge,
    goal: `${name} 동작을 정확하고 연속적으로 수행하며 도전 과제를 해결한다`,
    missions,
    feedback: [
      '미션 중 가장 어려웠던 것은? 왜?',
      `${skills} 동작이 처음보다 나아진 점이 있어?`,
    ],
  }
}

function buildEngage(tmpl, name, skills, equip) {
  return {
    minutes: tmpl.minutes.engage,
    goal: `${name}을(를) 게임 상황에서 적용하여 즐겁게 참여한다`,
    game: {
      name: `${name} 적용 게임`,
      description: `배운 ${skills}을(를) 활용하여 모둠 대항 미니게임을 진행한다.`,
      rules: [
        `${skills} 동작을 사용해야 점수를 인정한다`,
        '모둠원 전원 참여 필수',
        '안전 규칙 준수',
      ],
      equipment: equip,
    },
    scaffolding: {
      down: '규칙을 단순화하여 진행한다.',
      up: '추가 규칙(시간 제한, 공간 축소)을 적용한다.',
    },
  }
}

function buildWrapup(tmpl, name) {
  return {
    minutes: tmpl.minutes.wrapup,
    flow: [
      '정리운동: 스트레칭 2분',
      `오늘 ${name} 활동에서 배운 점 나누기`,
      '잘한 점 칭찬 + 다음 차시 예고',
    ],
    reflection: `오늘 ${name}을(를) 하면서 나는 어떤 점이 성장했을까?`,
  }
}
